askmark/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings # new

from django.conf.urls.static import static # new


urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

from django.conf.urls import url

app_name = 'blog'
urlpatterns = [
	path('', views.post_list, name = 'post_list'),
	path('popularpost', views.post_list, name = 'popularpost'),
	path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),

	path('<int:question_id>/', views.detail, name = 'detail'),
	path('<int:question_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),

	path('newpost/', views.newpost_page, name = 'newpost_page'),
	path('newpost/add', views.post_new, name='post_new'),

	path('createacc', views.createacc, name='createacc'),
	path('createacc/su', views.createacc_su, name='createaccsu'),

	path('change', views.change, name='change'),
	path('change/login', views.change_login, name='changelogin'),
]

askmark/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>

    <meta charset="utf-8">
    
    <title>{% block title %}AskMark{% endblock %}</title>

    <link rel="stylesheet" href="{% static "assert/style/bootstrap.min.css"%}">
  	<link rel="stylesheet" href="{% static "assert/style/style.css"%}">


</head>

<body>
<header class="fixed-top navbar-expand-lg navbar-light bg-light">
<div class="row">
    <div class="col-3 main-label"><a class="" href="{% url 'blog:post_list' %}">AskMark</a></div>
    <div class="col-3 input-group mb-3">
      <input type="text" class="form-control" placeholder="Введите название вопроса">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button">Поиск</button>
      </div>
    </div>

    {% block auth %} 
    {% if user.is_authenticated %}
    <div class="col-6 button-auth">
      <a href="{% url 'logout' %}"><button type="button" class="btn btn-outline-success">Выйти</button></a>
      <a href="{% url 'blog:change' %}"><button type="button" class="btn btn-outline-success">Настройки</b></button></a>
      <a href="{% url 'blog:change' %}"><button type="button" class="btn btn-outline-success">Привет, <b>{{user.username}}</b></button></a>
      <a href="{% url 'blog:newpost_page' %}"><button type="button" class="btn btn-outline-success">Задать новый вопрос</button></a>

    </div>
{% else %}
    <div class="col-6 button-auth">
      <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-success">Войти</button></a>
      <a href="{% url 'blog:createacc' %}"><button type="button" class="btn btn-outline-success">Зарегистрироваться</button></a>
    </div>
{% endif %}
    {% endblock %}

</div>
</header>

<div class="container content">
  
  <div class="row">
    <div class="col-8">
      {% block content %}{% endblock %}
    </div>


    <div class="col-4 bg-light main-sidebar">
      <h3>Популярные теги</h3>
      <ul class="list-group">
        <li class="list-group-item">Тег</li>
        <li class="list-group-item">Тег</li>
        <li class="list-group-item">Тег</li>
        <li class="list-group-item">Тег</li>
      </ul>
      <br>
      <h3>Лучшие пользователи</h3>
      <ul class="list-group">
        <li class="list-group-item">Пользователь</li>
        <li class="list-group-item">Пользователь</li>
        <li class="list-group-item">Пользователь</li>
        <li class="list-group-item">Пользователь</li>
      </ul>
    </div>

  </div>


{% block pagination %}
{% endblock %}


</div>
</body>

</html>

askmark/templates/change.html
{% extends 'base.html' %}

    {% block content %}
     {% if user.is_authenticated %}

    <h2 class="">Настройки</h2><a href="{% url 'password_change' %}"><button type="submit" class="btn btn-outline-success">Изменить пароль</button></a>
    <hr>




      <div class="row">
        <div class="col-3 label-form">
          <span><b>Ваш логин:</b> {{uname}}</span><hr>
          <span><b>Ваш email:</b> {{uemail}}</span><hr>
          <span><b>Ваше имя: </b>{{ufirstname}}</span><hr>
        </div>
      </div>

    <form action="{% url 'blog:changelogin' %}" method="POST">

        {% csrf_token %}

        {{mes}}
      <br>
      <br>
      <div class="row">
        <div class="col-2 label-form">
          <p>Новый логин</p><br>
          <p>Новый email</p><br>
          <p>Новое имя</p>
        </div>
        <div class="col-10 label-inputs">
          <input class="form-control" name="username">
          <input class="form-control" name="email">
          <input class="form-control" name="firstname">
          <button type="submit" class="btn btn-outline-success">Применить</button>
        </div>
      </div>

    </form>

    {% else %}

    <p>Чтобы сменить логин, необходимо войти!</p>
    

    {% endif %}
      
    {% endblock %}


{% block title %}Настройки{% endblock %}

askmark/templates/create_acc.html
{% extends 'base.html' %}

    {% block content %}
     {% if user.is_authenticated %}

    <p>Вы уже зарегистрированы</p>

    {% else %}

    <h2 class="">Создайте аккаунт</h2>

    <form action="{% url 'blog:createaccsu' %}" method="POST">

        {% csrf_token %}

        {{mes}}
      <br>
      <br>
      <div class="row">
        <div class="col-2 label-form">
          <p>Логин</p><br>
          <p>email</p><br>
          <p>Пароль</p>
        </div>
        <div class="col-10 label-inputs">
          <input class="form-control" name="username">
          <input class="form-control" type="email" name="email">
          <input class="form-control" type="password" name="password">
          <button type="submit" class="btn btn-outline-success">Зарегистрироваться</button>
        </div>
      </div>

    </form>

    {% endif %}
      
    {% endblock %}


{% block title %}Зарегистрироваться{% endblock %}

askmark/templates/detail.html
{% extends 'base.html' %}

{% block title %}{{question.question_title}}{% endblock %}

  {% block content %}

      <h2 class="label-new-questions">{{question.question_title}}</h2>
      <em>{{question.pub_date}}</em>
      <br>
      <span>Теги:</span>
      <span class="style-of-new-posts">{% for tag in question.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}"> {{ tag.name }}</a> |
            {% endfor %}
      </span>
      <br>
      <br>

        <img class="prev-img" src="{{question.author_id.profile.img.url}}">

      <br>
      <br>
      <span>Автор:</span>
      <span><b>{{question.author_id}}</b></span>
      <br>
      <br>
      <p>{{question.article_text|linebreaksbr}}</p>
      
      

      <hr>
          
      <p>Ответов: <b>{{answers_list_count}}</b></p>

      {% if answers_list %}
        {% for c in answers_list %}
        <hr>
        <img class="prev-img-ans" src="{{c.author_id.profile.img.url}}">

            
            <span><strong>{{c.author_id}}: </strong></span>
            <span>{{c.answer_text}}</span>
          {% endfor %}
        {% else %}
          <p>Пока нет комментариев</p>
        {% endif %}
      <hr>

    <form action="{% url 'blog:leave_comment' question.id %}" method="POST">
      
      {% csrf_token %}

      <div class="row">
        <div class="col-2 label-form">
          <p>Ответ</p>
        </div>
        <div class="col-10 label-inputs">
          <textarea name="text" class="form-control"></textarea>
          <button type="submit" class="btn btn-outline-success">Ответить</button>
        </div>
      </div>
    </form>

      
  {% endblock %}







{% block pagination %}{% endblock %}

askmark/templates/index.html
{% extends 'base.html' %}

      {% block content %}
      {% if tag %}
            <h2 class="label-new-questions">Статьи с тегом #{{ tag.name }}</h2>
      {% else %}
      <h2 class="label-new-questions">Новые вопросы</h2>
      {% endif %}
      
        {% if posts %}
          {% for a in posts %}



            <div class="prev-post row style-of-new-posts">
              <div class="col-3">
                <br>
                <img class="prev-img" src="{{a.author_id.profile.img.url}}">
              </div>
              <div class="col-9">
                <h4 class="name-label"><a class="style-of-new-posts" href="{% url 'blog:detail' a.id %}">{{a.question_title}}</a></h4>
                <p>Пользователь: <b>{{a.author_id}}</b></p>
                <p>{{a.article_text }}</p>
                <a class="btn" href="{% url 'blog:detail' a.id %}" class="">Ответов:
                  {% for k, v in answers.items %}
                      {% if k ==  a.id %}
                          {{ v }}
                      {% endif %}
                  {% endfor %}
                </a>
                <br><br>
               <span>Теги:</span>
                <span>
                      {% for tag in a.tags.all %}
                        <a class="btn" href="{% url 'blog:post_list_by_tag' tag.slug %}"> {{ tag.name }}</a>
                      {% endfor %}
                </span>
              </div>
            </div>

          {% endfor %}
        {% else %}
          <p>Вопросов пока нет</p>
        {% endif %}
    {% endblock %}



{% block pagination %}
<div class="row style-of-new-posts">
  <div class="col-sm">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ questions.previous_page_number }}">предыдущая</a>
        {% endif %}

        

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">следующая</a>
            <a href="?page={{ posts.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>

  </div>
  <div class="col-sm">
    <span class="step-links">
            Страница {{ posts.number }} из {{ posts.paginator.num_pages }}
    </span>
  </div>
</div>
{% endblock %}

askmark/templates/newpost.html
{% extends 'base.html' %}

{% block title %}Новый пост{% endblock %}

  {% block content %}
  

    {% if user.is_authenticated %}

      <h2 class="">Новый вопрос</h2>
      <br>
      <form action="{% url 'blog:post_new' %}" method="POST">

        {% csrf_token %}
        <div class="form-new-post">

              {{ form.as_p }}
              <button type="submit" class="btn btn-outline-success">Задать вопрос</button>

        </div>

      </form>

    {% else %}

      <p>Для создания вопроса нужно авторизироваться!</p>

    {% endif %}
{% endblock %}










{% block pagination %}{% endblock %}

askmark/templates/post_list.html
{% extends 'base.html' %}

  {% block content %}
        {% if tag %}
            <h2 class="label-new-questions">Статьи с тегом "{{ tag.name }}"</h2>
        {% endif %}
            {% for post in posts %}
                <div class="post-preview">
                        <h2 class="post-title">
                            <a href="{% url 'post_detail' slug=post.slug %}">{{ post.question_title }}</a>
                        </h2>
                        <p>
                            {{ post.article_text }}
                        </p>
                    <p class="post-meta">Опубликовано {{ post.pub_date }}</p>
                    <p class="post-meta">
                        ТЕГИ:
                            {% for tag in post.tags.all %}
                            <a href="{% url 'post_list_by_tag' tag.slug %}"> {{ tag.name }}</a> |
                            {% endfor %}
                    </p>

                </div>
            {% endfor %}
{% endblock %}